Add cxx interop build pipeline
apple/swift-nio-ssl pull request #454
Opened 2023-12-19 18:34 UTC by gjcairo

This PR adds a new target to `docker-compose` that builds a new project that depends on this one, with C++ interoperability enabled, with the goal of adding a new CI pipeline that checks the build succeeds.

### Motivation:

To make sure that C++ interoperability can be used on projects that depend on `swift-nio-ssl`.

### Modifications:

- Added a new target to docker-compose that creates a new package that depends on `swift-ni-ssl`, and builds it with C++ interoperability enabled.
- Will request a new CI pipeline that runs this new target.

### Result:

We will ensure this projects builds properly with C++ interoperability enabled.

2023-12-20 08:06 UTC, glbrntt commented on scripts/cxx-interop-compatibility.sh
> +mkdir -p interop
Would be good if we can use temporary directory instead to avoid collisions and not clutter the checkout if this is run locally, for example.

2023-12-20 13:30 UTC, glbrntt approved these changes

2023-12-20 17:10 UTC, Lukasa requested changes
One quick nit and then we're good.

2023-12-20 17:10 UTC, Lukasa commented on scripts/cxx-interop-compatibility.sh
> +            swiftSettings: [.interoperabilityMode(.Cxx)]
I don't think we need the test target.

2023-12-20 17:37 UTC, yim-lee commented
@swift-server-bot add to allowlist

2023-12-20 19:45 UTC, gjcairo commented
@yim-lee can thanks for dealing with the pipelines!

2023-12-21 08:00 UTC, glbrntt commented on scripts/cxx-interop-compatibility.sh
> +                .product(name: "NIOSSLHTTP1Client", package: "swift-nio-ssl")
I don't think it makes sense to include these as they're executable targets

2024-01-02 13:55 UTC, Lukasa approved these changes

2024-01-02 13:55 UTC, merged